# Generated by Django 5.0.3 on 2024-05-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='email',
            field=models.EmailField(default='anu@gmail.com', max_length=254),
        ),
    ]
